import elementary from '@quarkly/elementary';

const Text = elementary.p({
  name: 'Text',
  styles: [
    'variant',
    'display',
    'height',
    'minHeight',
    'maxHeight',
    'width',
    'minWidth',
    'maxWidth',
    'size',
    'p',
    'pt',
    'pr',
    'pb',
    'pl',
    'px',
    'py',
    'm',
    'mt',
    'mr',
    'mb',
    'ml',
    'mx',
    'my',
    'fontSize',
    'color',
    'fontFamily',
    'fontWeight',
    'textAlign',
    'lineHeight',
    'letterSpacing',
    'flex',
    'order',
    'justifySelf',
    'alignSelf',
    'bg',
    'background',
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'backgroundRepeat',
    'border',
    'borderTop',
    'borderRight',
    'borderBottom',
    'borderLeft',
    'borderColor',
    'borderRadius',
    'opacity',
    'boxShadow',
    'overflow',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'zIndex',
  ],
  variant: 'texts',
  effects: {
    hover: ':hover',
  },
});

export default Text;
