import elementary from '@quarkly/elementary';

const Grid = elementary.div(
  {
    name: 'Grid',
    styles: [
      'variant',
      'display',
      'height',
      'minHeight',
      'maxHeight',
      'width',
      'minWidth',
      'maxWidth',
      'size',
      'p',
      'pt',
      'pr',
      'pb',
      'pl',
      'px',
      'py',
      'm',
      'mt',
      'mr',
      'mb',
      'ml',
      'mx',
      'my',
      'alignItems',
      'alignContent',
      'justifyItems',
      'justifyContent',
      'flexWrap',
      'flexBasis',
      'flexDirection',
      'flex',
      'order',
      'justifySelf',
      'alignSelf',
      'gridGap',
      'gridColumnGap',
      'gridRowGap',
      'gridColumn',
      'gridAutoFlow',
      'gridAutoColumns',
      'gridAutoRows',
      'gridTemplateColumns',
      'gridTemplateRows',
      'gridTemplateAreas',
      'gridArea',
      'bg',
      'background',
      'backgroundImage',
      'backgroundSize',
      'backgroundPosition',
      'backgroundRepeat',
      'gridGap',
      'border',
      'borderTop',
      'borderRight',
      'borderBottom',
      'borderLeft',
      'borderColor',
      'borderRadius',
      'opacity',
      'boxShadow',
      'overflow',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'zIndex',
    ],
    variant: 'grids',
    effects: {
      hover: ':hover',
    },
  },
  {
    display: 'grid',
  },
);

export default Grid;
