import elementary from '@quarkly/elementary';

const Link = elementary.a({
  name: 'Link',
  styles: [
    'variant',
    'href',
    'name',
    'target',
    'title',
    'display',
    'height',
    'minHeight',
    'maxHeight',
    'width',
    'minWidth',
    'maxWidth',
    'size',
    'padding',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
    'paddingX',
    'paddingY',
    'margin',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'marginX',
    'marginY',
    'fontSize',
    'color',
    'flex',
    'order',
    'justifySelf',
    'alignSelf',
    'background',
    'backgroundColor',
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'backgroundRepeat',
    'border',
    'borderTop',
    'borderRight',
    'borderBottom',
    'borderLeft',
    'borderColor',
    'borderRadius',
    'opacity',
    'boxShadow',
    'overflow',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'zIndex',
  ],
  variant: 'links',
  effects: {
    hover: ':hover',
    focus: ':focus',
    active: ':active',
  },
});

export default Link;
