import elementary from '@quarkly/elementary';

const Link = elementary.a({
  name: 'Link',
  styles: [
    'variant',
    'href',
    'name',
    'target',
    'title',
    'display',
    'height',
    'minHeight',
    'maxHeight',
    'width',
    'minWidth',
    'maxWidth',
    'size',
    'p',
    'pt',
    'pr',
    'pb',
    'pl',
    'px',
    'py',
    'm',
    'mt',
    'mr',
    'mb',
    'ml',
    'mx',
    'my',
    'fontSize',
    'color',
    'flex',
    'order',
    'justifySelf',
    'alignSelf',
    'bg',
    'background',
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'backgroundRepeat',
    'border',
    'borderTop',
    'borderRight',
    'borderBottom',
    'borderLeft',
    'borderColor',
    'borderRadius',
    'opacity',
    'boxShadow',
    'overflow',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'zIndex',
  ],
  variant: 'links',
  effects: {
    hover: ':hover',
    focus: ':focus',
    active: ':active',
  },
});

export default Link;
