import elementary from '@quarkly/elementary';
import { getOmitProps } from '../utils';

const Flex = elementary.div(
  {
    name: 'Flex',
    styles: [
      'variant',
      'display',
      'height',
      'minHeight',
      'maxHeight',
      'width',
      'minWidth',
      'maxWidth',
      'size',
      'padding',
      'paddingTop',
      'paddingRight',
      'paddingBottom',
      'paddingLeft',
      'paddingX',
      'paddingY',
      'margin',
      'marginTop',
      'marginRight',
      'marginBottom',
      'marginLeft',
      'marginX',
      'marginY',
      'alignItems',
      'alignContent',
      'justifyItems',
      'justifyContent',
      'flexWrap',
      'flexBasis',
      'flexDirection',
      'flex',
      'order',
      'justifySelf',
      'alignSelf',
      'gridGap',
      'gridColumnGap',
      'gridRowGap',
      'gridColumn',
      'gridAutoFlow',
      'gridAutoColumns',
      'gridAutoRows',
      'gridTemplateColumns',
      'gridTemplateRows',
      'gridTemplateAreas',
      'gridArea',
      'background',
      'backgroundColor',
      'backgroundImage',
      'backgroundSize',
      'backgroundPosition',
      'backgroundRepeat',
      'gridGap',
      'border',
      'borderTop',
      'borderRight',
      'borderBottom',
      'borderLeft',
      'borderColor',
      'borderRadius',
      'opacity',
      'boxShadow',
      'overflow',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'zIndex',
    ],
    variant: 'flexs',
    effects: {
      hover: ':hover',
    },
    omit: getOmitProps(),
  },
  {
    display: 'flex',
  },
);

export default Flex;
